export const GAME_CONFIG = {
  STORE_WIDTH: 1200,
  STORE_HEIGHT: 700,
  TICK_RATE: 60,
  DAY_DURATION: 30,
  OPEN_HOUR: 9,
  CLOSE_HOUR: 21,
  DAILY_RENT: 500,
  STAFF_SALARY: 150,
  BASE_CUSTOMERS_PER_DAY: 20,
  BOOK_COST_RATIO: 0.6,
  MEMBER_DISCOUNT: 0.85,

  SPACE_COMPRESSION_THRESHOLD: 50,
  SPACE_COMPRESSION_SEVERE: 75,
  SPACE_SALES_PENALTY_PER_POINT: 0.008,
  SPACE_BROWSE_PENALTY_PER_POINT: 0.006,
  COFFEE_QUEUE_IMPACT_THRESHOLD: 5,
  COFFEE_QUEUE_SLOW_FACTOR: 0.15,

  CRISIS_CHANCE: 0.2,
  CRISIS_MIN_HOUR: 12,
  CRISIS_MAX_HOUR: 18,
};

export const ACTIVITY_TYPES = {
  THEME_SHARING: {
    id: 'theme_sharing',
    name: '主题分享会',
    desc: '邀请嘉宾分享特定主题，吸引爱好者',
    cost: 300,
    popularityGain: 15,
    reputationGain: 5,
    spaceUsed: 20,
    duration: 3,
    customerBoost: 1.5,
    memberBoost: 1.2,
    color: 0x4a90d9,
    customerTypeWeights: { CASUAL: 0.15, READER: 0.35, STUDENT: 0.2, PROFESSIONAL: 0.2, FAMILY: 0.1 },
    boostedCategory: 'SCIENCE',
    canCrisis: true,
  },
  AUTHOR_MEETING: {
    id: 'author_meeting',
    name: '作者见面会',
    desc: '知名作家签售，大幅提升人气和销量',
    cost: 800,
    popularityGain: 30,
    reputationGain: 15,
    spaceUsed: 35,
    duration: 4,
    customerBoost: 2.5,
    memberBoost: 1.5,
    bookSalesBoost: 2.0,
    color: 0xd94a6b,
    customerTypeWeights: { CASUAL: 0.1, READER: 0.45, STUDENT: 0.15, PROFESSIONAL: 0.2, FAMILY: 0.1 },
    boostedCategory: 'LITERATURE',
    canCrisis: true,
  },
  KIDS_EXPERIENCE: {
    id: 'kids_experience',
    name: '儿童体验活动',
    desc: '亲子阅读和手工活动，吸引家庭客户',
    cost: 200,
    popularityGain: 10,
    reputationGain: 8,
    spaceUsed: 25,
    duration: 2,
    customerBoost: 1.8,
    memberBoost: 1.3,
    kidsBookBoost: 3.0,
    color: 0x7cd94a,
    customerTypeWeights: { CASUAL: 0.05, READER: 0.05, STUDENT: 0.15, PROFESSIONAL: 0.05, FAMILY: 0.7 },
    boostedCategory: 'CHILDREN',
    canCrisis: true,
  },
  NEW_BOOK_LAUNCH: {
    id: 'new_book_launch',
    name: '新书发布会',
    desc: '首发新书，限量优惠，刺激消费',
    cost: 400,
    popularityGain: 20,
    reputationGain: 10,
    spaceUsed: 15,
    duration: 2,
    customerBoost: 2.0,
    memberBoost: 1.8,
    newBookDiscount: 0.8,
    color: 0xd9a94a,
    customerTypeWeights: { CASUAL: 0.15, READER: 0.4, STUDENT: 0.15, PROFESSIONAL: 0.2, FAMILY: 0.1 },
    boostedCategory: 'BUSINESS',
    canCrisis: true,
  },
};

export const BOOK_CATEGORIES = {
  LITERATURE: { id: 'literature', name: '文学小说', basePrice: 45, popularity: 0.9 },
  SCIENCE: { id: 'science', name: '科普读物', basePrice: 55, popularity: 0.6 },
  HISTORY: { id: 'history', name: '历史人文', basePrice: 50, popularity: 0.5 },
  CHILDREN: { id: 'children', name: '儿童读物', basePrice: 35, popularity: 0.7 },
  BUSINESS: { id: 'business', name: '经管励志', basePrice: 50, popularity: 0.8 },
  ART: { id: 'art', name: '艺术设计', basePrice: 65, popularity: 0.4 },
};

export const CUSTOMER_TYPES = {
  CASUAL: {
    id: 'casual',
    name: '普通顾客',
    baseStayTime: 15,
    buyChance: 0.4,
    avgSpend: 50,
    memberChance: 0.1,
  },
  READER: {
    id: 'reader',
    name: '资深读者',
    baseStayTime: 45,
    buyChance: 0.7,
    avgSpend: 80,
    memberChance: 0.3,
  },
  STUDENT: {
    id: 'student',
    name: '学生顾客',
    baseStayTime: 30,
    buyChance: 0.5,
    avgSpend: 35,
    memberChance: 0.2,
  },
  PROFESSIONAL: {
    id: 'professional',
    name: '白领精英',
    baseStayTime: 25,
    buyChance: 0.6,
    avgSpend: 100,
    memberChance: 0.4,
  },
  FAMILY: {
    id: 'family',
    name: '家庭顾客',
    baseStayTime: 40,
    buyChance: 0.6,
    avgSpend: 120,
    memberChance: 0.35,
  },
};

export const MEMBER_LEVELS = {
  NONE: { id: 'none', name: '非会员', discount: 1.0, pointsRate: 0 },
  BRONZE: { id: 'bronze', name: '铜牌会员', discount: 0.95, pointsRate: 1, minSpend: 200 },
  SILVER: { id: 'silver', name: '银牌会员', discount: 0.9, pointsRate: 1.5, minSpend: 500 },
  GOLD: { id: 'gold', name: '金牌会员', discount: 0.85, pointsRate: 2, minSpend: 1000 },
  PLATINUM: { id: 'platinum', name: '钻石会员', discount: 0.8, pointsRate: 3, minSpend: 2000 },
};

export const CRISIS_TYPES = {
  INSTRUCTOR_CANCEL: {
    id: 'instructor_cancel',
    name: '讲师临时取消',
    desc: '活动讲师因故无法到场，需要紧急处理！',
    icon: '⚠️',
  },
};

export const CRISIS_OPTIONS = {
  STAFF_SHARING: {
    id: 'staff_sharing',
    name: '店员代为分享',
    desc: '让有经验的店员代替讲师进行分享',
    trustChange: -5,
    incomeRatio: 0.6,
    reputationChange: -3,
    popularityChange: -2,
    costRefund: 0,
    memberTrustMultiplier: 0.8,
  },
  POSTPONE: {
    id: 'postpone',
    name: '延期举办',
    desc: '通知顾客活动延期，择日重新举办',
    trustChange: -10,
    incomeRatio: 0.1,
    reputationChange: -8,
    popularityChange: -5,
    costRefund: 0.5,
    memberTrustMultiplier: 0.6,
  },
  REFUND: {
    id: 'refund',
    name: '全额退款',
    desc: '取消活动，为所有参与者全额退款',
    trustChange: -3,
    incomeRatio: 0,
    reputationChange: -5,
    popularityChange: -3,
    costRefund: 1.0,
    memberTrustMultiplier: 0.9,
  },
};

export const STAFF_ROLES = {
  CASHIER: { id: 'cashier', name: '收银员', desc: '提高结账效率，减少排队', salesBonus: 0.1 },
  GUIDE: { id: 'guide', name: '导购员', desc: '引导顾客找到书籍，提升购买率', buyBonus: 0.15 },
  BARISTA: { id: 'barista', name: '咖啡师', desc: '加快咖啡制作，减少排队影响', coffeeSpeedBonus: 0.3 },
  EVENT_STAFF: { id: 'event_staff', name: '活动专员', desc: '活动时可替代讲师，减少危机损失', crisisBonus: 0.3 },
};
