export const GAME_CONFIG = {
  STORE_WIDTH: 1200,
  STORE_HEIGHT: 700,
  TICK_RATE: 60,
  DAY_DURATION: 30,
  OPEN_HOUR: 9,
  CLOSE_HOUR: 21,
  DAILY_RENT: 500,
  STAFF_SALARY: 150,
  BASE_CUSTOMERS_PER_DAY: 20,
  BOOK_COST_RATIO: 0.6,
  MEMBER_DISCOUNT: 0.85,
};

export const ACTIVITY_TYPES = {
  THEME_SHARING: {
    id: 'theme_sharing',
    name: '主题分享会',
    desc: '邀请嘉宾分享特定主题，吸引爱好者',
    cost: 300,
    popularityGain: 15,
    reputationGain: 5,
    spaceUsed: 20,
    duration: 3,
    customerBoost: 1.5,
    memberBoost: 1.2,
    color: 0x4a90d9,
  },
  AUTHOR_MEETING: {
    id: 'author_meeting',
    name: '作者见面会',
    desc: '知名作家签售，大幅提升人气和销量',
    cost: 800,
    popularityGain: 30,
    reputationGain: 15,
    spaceUsed: 35,
    duration: 4,
    customerBoost: 2.5,
    memberBoost: 1.5,
    bookSalesBoost: 2.0,
    color: 0xd94a6b,
  },
  KIDS_EXPERIENCE: {
    id: 'kids_experience',
    name: '儿童体验活动',
    desc: '亲子阅读和手工活动，吸引家庭客户',
    cost: 200,
    popularityGain: 10,
    reputationGain: 8,
    spaceUsed: 25,
    duration: 2,
    customerBoost: 1.8,
    memberBoost: 1.3,
    kidsBookBoost: 3.0,
    color: 0x7cd94a,
  },
  NEW_BOOK_LAUNCH: {
    id: 'new_book_launch',
    name: '新书发布会',
    desc: '首发新书，限量优惠，刺激消费',
    cost: 400,
    popularityGain: 20,
    reputationGain: 10,
    spaceUsed: 15,
    duration: 2,
    customerBoost: 2.0,
    memberBoost: 1.8,
    newBookDiscount: 0.8,
    color: 0xd9a94a,
  },
};

export const BOOK_CATEGORIES = {
  LITERATURE: { id: 'literature', name: '文学小说', basePrice: 45, popularity: 0.9 },
  SCIENCE: { id: 'science', name: '科普读物', basePrice: 55, popularity: 0.6 },
  HISTORY: { id: 'history', name: '历史人文', basePrice: 50, popularity: 0.5 },
  CHILDREN: { id: 'children', name: '儿童读物', basePrice: 35, popularity: 0.7 },
  BUSINESS: { id: 'business', name: '经管励志', basePrice: 50, popularity: 0.8 },
  ART: { id: 'art', name: '艺术设计', basePrice: 65, popularity: 0.4 },
};

export const CUSTOMER_TYPES = {
  CASUAL: {
    id: 'casual',
    name: '普通顾客',
    baseStayTime: 15,
    buyChance: 0.4,
    avgSpend: 50,
    memberChance: 0.1,
  },
  READER: {
    id: 'reader',
    name: '资深读者',
    baseStayTime: 45,
    buyChance: 0.7,
    avgSpend: 80,
    memberChance: 0.3,
  },
  STUDENT: {
    id: 'student',
    name: '学生顾客',
    baseStayTime: 30,
    buyChance: 0.5,
    avgSpend: 35,
    memberChance: 0.2,
  },
  PROFESSIONAL: {
    id: 'professional',
    name: '白领精英',
    baseStayTime: 25,
    buyChance: 0.6,
    avgSpend: 100,
    memberChance: 0.4,
  },
  FAMILY: {
    id: 'family',
    name: '家庭顾客',
    baseStayTime: 40,
    buyChance: 0.6,
    avgSpend: 120,
    memberChance: 0.35,
  },
};

export const MEMBER_LEVELS = {
  NONE: { id: 'none', name: '非会员', discount: 1.0, pointsRate: 0 },
  BRONZE: { id: 'bronze', name: '铜牌会员', discount: 0.95, pointsRate: 1, minSpend: 200 },
  SILVER: { id: 'silver', name: '银牌会员', discount: 0.9, pointsRate: 1.5, minSpend: 500 },
  GOLD: { id: 'gold', name: '金牌会员', discount: 0.85, pointsRate: 2, minSpend: 1000 },
  PLATINUM: { id: 'platinum', name: '钻石会员', discount: 0.8, pointsRate: 3, minSpend: 2000 },
};
